apiVersion: v1
kind: Service
metadata:
  name: service-genesis
  namespace: cage
spec:
  selector:
    app: service-genesis
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
