apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-outbox-worker
  namespace: cage
  labels:
    app: service-outbox-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-outbox-worker
  template:
    metadata:
      labels:
        app: service-outbox-worker
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "service-outbox-worker"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: service-outbox-worker
        image: harbor.maclab.wynnmacau.com/cage/service-outbox-worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MongoDB__ConnectionString
          valueFrom:
            secretKeyRef:
              name: cage-secrets
              key: mongodb-connection-string
        - name: MongoDB__DatabaseName
          value: "cage"
        - name: nacos__ServerAddresses__0
          value: "http://172.19.201.142:30080/"
        - name: nacos__UserName
          value: "nacos"
        - name: nacos__Password
          valueFrom:
            secretKeyRef:
              name: cage-secrets
              key: nacos-password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
