apiVersion: v1
kind: Service
metadata:
  name: service-query
  namespace: cage
spec:
  selector:
    app: service-query
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
