apiVersion: v1
kind: Service
metadata:
  name: saga-coordinator
  namespace: cage
spec:
  selector:
    app: saga-coordinator
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
